name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build_tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install hatch hatch-vcs
      - name: Build project
        run: hatch build
      - name: Echo deployment message
        run: echo "my-arithmetic-${{ github.actor }} deployment on stable servers"
      - name: List dist directory
        run: ls -l dist/

  build_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install hatch hatch-vcs
      - name: Build project
        run: hatch build
      - name: Echo deployment message
        run: echo "my-arithmetic-${{ github.actor }} deployment on develop servers"
      - name: List dist directory
        run: ls -l dist/

  test:
    runs-on: ubuntu-latest
    needs: [build_develop]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Hatch
        run: pip install hatch hatch-vcs
      - name: Run tests
        run: hatch test

  deploy_docs:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install sphinx sphinx-rtd-theme sphinxcontrib-napoleon
      - name: Build documentation
        run: |
          cd docs
          make html
      - name: Deploy to Read the Docs
        run: |
          pip install readthedocs-sphinx-ext
          rtd-build

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install coverage coveralls
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
      - name: Upload coverage to Coveralls
        run: coveralls