name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build_tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install hatch hatch-vcs
      - name: Build project
        run: hatch build
      - name: Echo deployment message
        run: echo "my-arithmetic-${{ github.actor }} deployment on stable servers"
      - name: List dist directory
        run: ls -l dist/

  build_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install hatch hatch-vcs
      - name: Build project
        run: hatch build
      - name: Echo deployment message
        run: echo "my-arithmetic-${{ github.actor }} deployment on develop servers"
      - name: List dist directory
        run: ls -l dist/

  test:
    runs-on: ubuntu-latest
    needs: [build_develop]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch run test:test